name: Asset-Deploy

on:
  pull_request:
    branches:
      - main

jobs:
  sonarqube-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
  
  docker-deploy:
    needs: sonarqube-check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Web Image
        run: |
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/asset-web:latest
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

  trivy-scan:
    needs: docker-deploy
    runs-on: ubuntu-latest

    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: image
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/asset-web:latest
          format: "table"
          exit-code: "0"
          ignore-unfixed: false
          severity: "CRITICAL,HIGH,MEDIUM"
          vuln-type: "os,library"
