name: dev-action

on:
  pull_request:
    branches:
      - dev

jobs:
  docker-deploy:
    permissions:
      contents: read
      pull-requests: write
    needs: blackduck-scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Web Image
        run: |
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/asset-dev-web:latest
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

  trivy-scan:
    permissions:
      contents: read
      pull-requests: write
    needs: docker-deploy
    runs-on: ubuntu-latest

    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: image
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/asset-dev-web:latest
          format: "table"
          exit-code: "0"
          ignore-unfixed: false
          severity: "CRITICAL,HIGH,MEDIUM"
          vuln-type: "os,library"
